### ISSUE TITLE
Authentication/Authorisation Failure

### ISSUE THREAD

**Issue by pekatete** [paypal/adaptiveaccounts-sdk-dotnet#6]
Has the classic sdk been discontinued?
I have been using my implementation for the last few years but today I can not connect, I get the error which I've attached on the image below:
```
errorCodeField: 10002
ShertMessage: Authentication/Authorisation failed.
LongMessage: You do not have permission to make this API call
```
![autherrpaypalsdk](https://cloud.githubusercontent.com/assets/3041243/19612527/09a46c90-97df-11e6-9390-3b5af1153a73.png)
 Needless to say, I my credentials are correct.

**Comment by pp-randy** [comment]
The Classic API is still up and running.  A few things could explain this but for the first check please confirm the credentials on the sandbox account.  PayPal Developer should give you access to your sandbox accounts here: https://developer.paypal.com/developer/accounts/ then just click Profile on the account.

**Comment by pp-randy** [comment]
Actually, what API call are you making and can you give me the correlation id from the error response?

**Comment by pekatete** [comment]
Apologies, I should have updated and / or closed this.
I encountered this issue with one of my apps which, as mentioned, I'd been using for years (that I recently update to a Win10 app) and thought the API had been deprecated. however, on running the in-updated app, I could connect as normal, so it seems the error (still in-resolved) was caused by my own code refactoring.
